
API_KEY = ''
API_SECRET = ''
RSI_OVERSOLD_UPTREND = 33
RSI_OVERBOUGHT_UPTREND = 82
RSI_OVERSOLD_DOWNTREND = 22
RSI_OVERBOUGHT_DOWNTREND = 69
TREND_MA = 60
RSI_TIME_PERIOD = 4
STOPLOSS_PERCENT = 12
COOLDOWN_SECONDS = 2700

supported_coins = ['LTC']
